### ISSUE TITLE
Cakeshop not available

### ISSUE THREAD

**Issue by brampurnot** [ConsenSys/quorum-wizard#111]
Hi guys,

not sure if these are bugs or if it works as designed but I used quorum-wizard to create a local network for development purposes. I selected a custom setup and configured some additional stuff. I also indicated that I wanted to use cakeshop. 

When I look at the config.json file, I see thee following:
"cakeshop": "none"

Is this the reason why Cakeshop is not working? What should be the parameter to activate this? Also I'm wondering why the state of my contracts are not kept after a reboot of my laptop. I need to redeploy the contract everytime and reset the state to what it was (which is a bit of a pain; not a showstopper but I would expect it to keep its state).

Thanks,
Bram

**Comment by bmcd** [comment]
The tools selection question is a multi-select, so make sure you're pressing spacebar to select cakeshop before you press enter. If you just press enter then no tools will actually be selected.

As for the state, are you using bash or docker-compose for your network? The stop script for docker compose networks just runs `docker-compose down`, which stops all the containers and deletes everything. You could instead maybe call `docker-compose stop` so that it doesn't delete the containers' volumes. I'm not sure if that survives computer restarts though, so you may need to experiment with it.

**Comment by brampurnot** [comment]
Thanks I'll give it a shot
