### ISSUE TITLE
Config log level of container node quorum (Quorum wizard)

### ISSUE THREAD

**Issue by conglt10** [ConsenSys/quorum-wizard#123]
Hi everyone, I am using quorum wizard to generate quorum network with option docker-compose (Tessera and Raft consensus). Now, I want to config log level of docker container tessera node (only ERROR log is printed). Do you support me ? Thank you !

![Screenshot from 2020-12-02 16-07-45](https://user-images.githubusercontent.com/53574829/100852078-91d1ba80-34b8-11eb-9289-f1913de64ac4.png)

**Comment by SatpalSandhu61** [comment]
Instructions on changing the Tessera log level can be found here: https://docs.tessera.consensys.net/en/latest/HowTo/Use/Logging/#to-change-the-default-log-level
(The default logging level should already be "INFO" though.)

If you do need to change the logging level, then you'll need to change the startup command line for Tessera as described in the instructions. Since you are using docker, I suggest the following:
1) Create a `logback.xml` file for each tessera instance, under the configuration that was created by quorum-wizard (e.g. `qdata/c1/logback.xml`, `qdata/c2/logback.xml` etc
2) Modify `docker-compose.yml` and change the tessera startup to use the logback file, e.g.:
```
          java -Dlogback.configurationFile=$${DDIR}/logback.xml -Xms128M -Xmx128M -jar /tessera/tessera-app.jar -configfile $${DDIR}/tessera-config$${TESSERA_CONFIG_TYPE}.json
```

**Comment by bmcd** [comment]
Those look like geth logs to me, not tessera. To change the geth log level, look in the docker-compose.yml file for the `geth` command, and change the verbosity flag (default looks to be `--verbosity 5`) to a lower number: 0=silent, 1=error, 2=warn, 3=info, 4=debug, 5=detail

Also, if you just want to quickly change the tessera logs, you can add `-Dverbosity=DEBUG` (or whatever level you want) to the `java` command in the docker-compose file. The default logback file uses this property to set the default log level for most of its logs. Not as fine-grained as adding your own logback file, but it works.

**Comment by conglt10** [comment]
> Those look like geth logs to me, not tessera. To change the geth log level, look in the docker-compose.yml file for the `geth` command, and change the verbosity flag (default looks to be `--verbosity 5`) to a lower number: 0=silent, 1=error, 2=warn, 3=info, 4=debug, 5=detail
> 
> Also, if you just want to quickly change the tessera logs, you can add `-Dverbosity=DEBUG` (or whatever level you want) to the `java` command in the docker-compose file. The default logback file uses this property to set the default log level for most of its logs. Not as fine-grained as adding your own logback file, but it works.

thank you very much
