### ISSUE TITLE
Raft not being created, always istanbul

### ISSUE THREAD

**Issue by zaidmunir** [ConsenSys/quorum-wizard#129]
I have create a simple network and also tried with custom network. The docker-compose file does not generate proper config for raft. Infact it is always using quorum consensus as istanbul. I have tried many times.
![Screenshot from 2021-03-09 12-59-29](https://user-images.githubusercontent.com/2095087/110437727-7e497780-80d7-11eb-9528-edda701891d9.png)
![Screenshot from 2021-03-09 12-59-22](https://user-images.githubusercontent.com/2095087/110437735-80abd180-80d7-11eb-904f-b29060e6e164.png)
![Screenshot from 2021-03-09 12-59-03](https://user-images.githubusercontent.com/2095087/110437738-81dcfe80-80d7-11eb-8d1d-9caae6e6a61a.png)

**Comment by bmcd** [comment]
The ${ENV_VAR_HERE:-XXXXX} pattern will use the environment variable if it exists, otherwise it will use the default value (where the XXXXX part is). The wizard creates a file called `.env` where it puts these environment variables. Docker-compose loads this file automatically.

After you start the network you should be able to do `./attach.sh 1` to attach to the geth node and see if it has raft as one of the rpc modules you can use.
